name: PARCELS
channels:
  - conda-forge
dependencies:
  - python=3
  - cartopy
  - cf_xarray
  - cftime
  - dask
  - folium
  - geopandas
  - jupyter
  - matplotlib-base
  - netcdf4
  - numpy
  - pandas
  - parcels
  - pooch
  - shapely
  - tqdm
  - xarray
  - xmovie
