name: PARCELS
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cartopy >=0.21
  - cf_xarray
  - cftime
  - contextily
  - dask
  - ffmpeg
  - folium
  - geopandas
  - humanize
  - jupyter
  - matplotlib-base
  - mpi4py
  - mpich
  - nbclassic
  - nco
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - parcels
  - pooch
  - pyogrio
  - scikit-learn
  - seaborn
  - shapely
  - tqdm
  - trajan
  - utide
  - xarray
  - xmovie
  - xoak
platforms:
  - linux-64
